//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DataBaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public int id_client { get; set; }
        public int id_point { get; set; }
        public System.DateTime date { get; set; }
        public int id_product { get; set; }
        public string code { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual PickPoint PickPoint { get; set; }
        public virtual Product Product { get; set; }
    }
}
